---
server:
  port: 80

spring:
  profiles:
    active: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/burakozturk/microservices-with-cloud-tools.git
          search-paths: configuration/docker